services:
  hustlesasa_recommendation_engine:
    platform: linux/amd64
    build: .
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 7777 --reload
    container_name: hustlesasa_recommendation_engine
    volumes:
      - .:/code
    ports:
      - "7777:7777"
